verbose added

diff --git a/client/Dockerfile b/client/Dockerfile
--- a/client/Dockerfile
+++ b/client/Dockerfile
@@ -3,7 +3,7 @@ FROM node:20 AS build
 WORKDIR /app
 COPY . .
 RUN npm install
-RUN npm run build
+RUN npm run build || (echo "BUILD FAILED" && ls -la && cat ./path-to-any-log-if-any && exit 1)
 
 # Serve with nginx
 FROM nginx:alpine
